import Head from 'next/head'

import { useEffect, useRef } from 'react'

import {init, step, resize, mouseUpdate, addKeyUp, addKeyDown, addEntity} from '../engine/index';
import { TestEntity1 } from './../domain/TestEntity1';

let singletoned = false;

export default function Home() {
  const canvasRef = useRef(null);

  useEffect(() => {
    if (singletoned) {
      return;
    }

    singletoned = true;

    const render = () => {
      step();

      requestAnimationFrame(render);
    }

    // Init
    document.addEventListener('resize', () => {
      const canvas = canvasRef.current as unknown as HTMLCanvasElement;

      resize(canvas.width, canvas.height);
    });

    document.addEventListener('mousemove', (e) => {
      const canvas = canvasRef.current as unknown as HTMLCanvasElement;

      const x = e.clientX - canvas.offsetLeft;
      const y = e.clientY - canvas.offsetTop;

      mouseUpdate({ x, y });
    });

    document.addEventListener('mousedown', (e) => {
      mouseUpdate({down: true, up: false, pressed: true });

      e.preventDefault();
    });

    document.addEventListener('mouseup', (e) => {
      mouseUpdate({down: false, up: true, released: true });

      e.preventDefault();
    });

    document.addEventListener('mousewheel', (e) => {
      mouseUpdate({wheel: (e as any).deltaY });
    });

    document.addEventListener('keyup', (e) => {
      addKeyUp(e.key);
    });

    document.addEventListener('keydown', (e) => {
      addKeyDown(e.key);
    });

    // Setup engine

    init(canvasRef.current as unknown as HTMLCanvasElement);

    render();
    // setup game?


    addEntity(new TestEntity1('Manolo'));
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div >
          <canvas id='mainCanvas' ref={canvasRef} />
        </div>
      </main>
    </>
  )
}
